### ISSUE TITLE
multiplot.phylo4d() data.xlim

### ISSUE THREAD

**Issue by marknovak** [fkeck/phylosignal#1]
Hi there,
Could you please provide an example for using data.xlim in ```multiplot.phylo4d()``` for multiple traits with different axis limits?  The description seems simple enough, yet I can't get the axes to be different.  (They all end up being the same as the first provided axis range.)
I've tried, for example, ```xlims<-matrix(c(0,1,0,2,-1,1),nrow=3,byrow=TRUE)``` and its transpose.
The description also references a Details section, which apparently doesn't exist(?)
thanks

**Comment by fkeck** [comment]
Hi,
data.xlim takes a 2 x n.trait matrix, each column corresponding to a trait. Your code should work with the transpose. It works with [the standard example](http://www.francoiskeck.fr/phylosignal/demo_plots.html).

     xlims <- matrix(c(0,1,0,2,-1,1),nrow=3,byrow=TRUE)
     multiplot.phylo4d(p4d, data.xlim = t(xlims))

I would need a reproducible example to be more specific.

**Comment by marknovak** [comment]
You're quite right.  It works as intended.  I had an error in my code.
Thanks for the quick response!  (Nice package, by the way.)

**Comment by fkeck** [comment]
Good and thank you. I close.
