### ISSUE TITLE
scaling method in barplot.phylo4d?

### ISSUE THREAD

**Issue by lschiebelhut** [fkeck/phylosignal#12]
I am unable to find the specific scaling method used in the documentation and I am unable to work it out from the code. Can you indicate what method is used, please?

**Comment by fkeck** [comment]
Can you post your code so I can reproduce your issue, please?

**Comment by lschiebelhut** [comment]
The code performs fine (and plot is below):
barplot.phylo4d(echinoTree.phylo4d)

By default, center = TRUE and scale = TRUE

All I can find in the documentation is:
center = a logical indicating whether traits values should be centered.
scale = a logical indicating whether traits values should be scaled.

I was able to find more details about centering in another issue post:
fkeck on Oct 10, 2019: "Centering a variable simply means to subtract the values by the mean of the values."

But I can't find any additional information about what specific scaling method is used in by barplot.phylo4d.

Thanks for your help.
<img width="790" alt="Screen Shot 2022-01-13 at 7 17 27 AM" src="https://user-images.githubusercontent.com/25267803/149358337-0fe335e2-dd53-4d05-97f0-5f91bff7ebd2.png">

**Comment by fkeck** [comment]
This is based on the R base function scale :
https://stat.ethz.ch/R-manual/R-devel/library/base/html/scale.html

> If center is TRUE then centering is done by subtracting the column means (omitting NAs) of x from their corresponding columns, and if center is FALSE, no centering is done.
> If scale is TRUE then scaling is done by dividing the (centered) columns of x by their standard deviations if center is TRUE, and the root mean square otherwise. If scale is FALSE, no scaling is done.

I hope it helps.

**Comment by lschiebelhut** [comment]
Yes! Thank you for the clarification. Much appreciated!

Best,
Lauren
