### ISSUE TITLE
Color code character states

### ISSUE THREAD

**Issue by JCGiron** [fkeck/phylosignal#5]
Hi,
I know the package is meant to be used with continuous traits, but I would like to use the dotplot command to plot a series of categorical traits for visualization purposes, as I intend to show that certain groups in my phylogeny share several traits.
Some of my characters are binary, some multistate (maximum 4 states), six characters in total.
I would like to color state 0 in blue, state 1 in green, state 2 in red, and state 3 in cyan across my character matrix.
I'm not an experienced coder. So far I managed to create a vector for colors: 
colst<-c("red","green","blue","cyan")
and applied it to my dotplot (which of course didn't work as intended)...
![image](https://user-images.githubusercontent.com/37313282/61342835-3e05f900-a811-11e9-9fed-d05bfa9162ca.png)
Thanks in advance for any help.
Then I will need to figure out how to adjust the x axis to show my character states and get rid of the 0 line marker.

**Comment by fkeck** [comment]
Hi,
First, in case you missed it, have look to this help page: http://www.francoiskeck.fr/phylosignal/demo_plots.html

I assume you loaded correctly your data in a phylo4d object named "p4d"
Your trait data can be extracted in a new matrix trait_mat. Then you create another one of same dimensions to specify your colors with:
```
trait_mat <- tdata(p4d, "tip")
col_mat <- matrix(NA, nrow = nrow(trait_mat), ncol = ncol(trait_mat))
```

Then you have to fill this new matrix col_mat with your color scheme.
```
col_mat[trait_mat == 0] <- "blue"
col_mat[trait_mat == 1] <- "green"
```
... and so on...

Finally use this matrix in the dot.col argument of dotplot:
`dotplot(p4d, dot.col = col_mat, center = FALSE, scale = FALSE)`


For customizing the plot, have a look to the argument of the multiplot.phylo4d function.
But I think it will be complicated to get rid of the zero line.

**Comment by JCGiron** [comment]
It worked perfectly for what I needed. Thank you very much!
