### ISSUE TITLE
centering the barplot.phylo4d plot changes the meaning of phylogeny of trait

### ISSUE THREAD

**Issue by Jigyasa3** [fkeck/phylosignal#6]
Hey @mrhelmus  and @fkeck 

I wanted to ask about barplot.phylo4d command. 
If I center the trait values and scale them, then this happens-
![image](https://user-images.githubusercontent.com/21186292/66560569-a9523380-eb92-11e9-9387-734ed3dcc505.png)

If I don't center or scale them, then this happens-
![image](https://user-images.githubusercontent.com/21186292/66560656-c6870200-eb92-11e9-8c3e-b25b1927985b.png)

The help document says that center=TRUE, just centers the values. But with and without centering, the visual representation means two very different things. With center =TRUE, the trait is negative? I checked, my data doesn't have negative values.

Codes used-
>p4d <- phylo4d(pruned.trees_higher, nitrogen_merged2_sorted_higher)
>carni.lipa <- lipaMoran(p4d)
>carni.lipa.p4d <- lipaMoran(p4d, as.p4d = TRUE)
>pvalues<-carni.lipa$p.value < 0.05
>rownames(pvalues)[pvalues[,1]==TRUE] #printing the values with signficant pvalue

#plot without centering and sorting-
>barplot.phylo4d(p4d, bar.col=(carni.lipa$p.value < 0.05) + 1, center = FALSE , scale = FALSE ,bar.lwd = 5,tip.font = 1,tip.cex=0.5)

#plot with centering and sorting-
>barplot.phylo4d(p4d, bar.col=(carni.lipa$p.value < 0.05) + 1, center = TRUE , scale = TRUE ,bar.lwd = 5,tip.font = 1,tip.cex=0.5)
 
What am I doing wrong here? 
Thanks!

**Comment by fkeck** [comment]
Hi @Jigyasa3 ,
I think nothing is wrong here. Centering a variable simply means to subtract the values by the mean of the values. This will automatically generate negative value. Note this is the default behavior of the barplot.phylo4d function.

**Comment by Jigyasa3** [comment]
Thank you for replying @fkeck! 
So does the negative values mean, that there is a negative correlation with the trait? 
Does a trait having a value less than the mean, affects it's interpretation using the statistical test?

**Comment by fkeck** [comment]
The negative values means nothing. They are just smaller than the mean in the original data. They will not affect the test.
